Component testing initial setup
nightwatchjs/create-nightwatch pull request #77
Opened 2022-11-21 20:24 UTC by harshit-bs

2022-11-22 12:53 UTC, vishalshah133 commented
Hey, @beatfactor  Can we update the 1st question to single select with the following options?
End to End
Component
Both

Lesser things to read and lesser actions

2022-11-23 09:10 UTC, beatfactor commented
> Hey, @beatfactor Can we update the 1st question to single select with the following options? End to End Component Both
> 
> Lesser things to read and lesser actions

I'm not sure. The next question will be a multi-select (browsers) so that's why I thought that we could keep the same design. We will also have API testing soon, so then we would have to change the design if we go for the single select.

2022-12-01 10:29 UTC, beatfactor commented on assets/component-config/vite.config.js
> +import nightwatchPlugin from 'vite-plugin-nightwatch';
I don't think we need to generate a vite config file at this point. In most cases, there will already be one, but if not, each plugin has its own vite config file with everything needed.

2022-12-01 10:35 UTC, beatfactor commented on src/constants.ts
> +        return 'localhost:5173';
```suggestion
        return 'http://localhost:5173';
```

2022-12-01 10:36 UTC, beatfactor commented on src/constants.ts
> +      } else if (answers.uiFramework === 'storybook') {
```suggestion
      }
      
      if (answers.uiFramework === 'storybook') {
```

2022-12-02 08:45 UTC, beatfactor commented on src/init.ts
> +        const viteSrcPath = path.join(componentConfigPath, 'vite.config.js');
no need to add vite.config files

2022-12-02 10:35 UTC, beatfactor requested changes
I think we need a few more tests here.

2022-12-09 08:33 UTC, merged